### ISSUE TITLE
Cannot find user while using /track

### ISSUE THREAD

**Issue by cimo95** [kabiiQ/FBK#6]
**Describe the bug**
I have tried to track a user [@ReiKitsukano](https://twitter.com/ReiKitsukano) but it result that FBK cant find this user.
I have tried using many possible ways like manually specify site and using /usetrack, etc

**Expected behavior**
FBK should be find this user since the profile is public 

**Screenshots**
![image](https://github.com/kabiiQ/FBK/assets/34116129/2011d668-3c3a-48d5-b31e-a4f5c122f4c2)

**Did the error occur on the publicly hosted version of the bot?**
Yes

**Comment by kabiiQ** [comment]
More broadly, the Twitter tracker had a main component not working in general. This will happen nowadays, as Twitter is difficult to access nowadays and the feature pretty randomly requires manual intervention.

Thanks for the report. Despite more servers using this feature than ever before, I haven't been having people report issues lately for some reason (used to receive fairly quick questions on Discord). Though I think people are being patient since Twitter is a challenge nowadays, I still need to know as I'm not staring at it lol. I may need to find some way to notify myself when errors increase for next time, but I don't have anything for that currently. 

It should be back online now.
